CREATE TABLE USER (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(45),
EMAIL VARCHAR(100),
IMAGEURL VARCHAR(300),
EMAILVERIFIED BOOLEAN DEFAULT FALSE,
PASSWORD VARCHAR(50),
PROVIDER VARCHAR(50),
PROVIDERID VARCHAR(50),
CONSTRAINT UC_EMAIL UNIQUE (EMAIL)
);